version: "3.9"

services:
    fullstack:
        network_mode: host
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: /bin/bash
        volumes:
            - .:/app
            - ~/.git:/home/cpot/.git
            - ~/.ssh:/home/cpot/.ssh
        ports:
            - 8000:8000
            - 3000:3000
            - 8081:8081
            - 1234:1234
        depends_on:
            - redis
            - postgresql
            - keycloak
        shm_size: 4gb
    redis:
        image: 'bitnami/redis:latest'
        ports:
            - 6355:6355
        network_mode: host
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_PORT_NUMBER=6355
    postgresql:
        image: timescale/timescaledb-ha:pg15-ts2.11
        restart: always
        volumes:
            - "$HOME/postgresql-data/cpot:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=cpot
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=passyword
            - PGPORT=5455
        network_mode: host
        ports:
            - 5455:5455
    keycloak:
        image: quay.io/keycloak/keycloak:21.1.2
        restart: always
        command: start-dev
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB=postgres
            - KC_DB_URL_HOST=localhost
            - KC_DB_URL_PORT=5455
            - KC_DB_USERNAME=postgres
            - KC_DB_PASSWORD=passyword
        network_mode: host
        ports:
            - 8080:8080
        depends_on:
            - postgresql
