# Generated by Django 4.2.1 on 2023-06-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
