[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Paul Bailey", email = "paul@neutron.studio"},
]
dependencies = [
    "django>=4.2.1",
]
requires-python = ">=3.10"
license = {text = "BSDv3"}
