# Generated by Django 4.2.1 on 2023-06-02 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='moderators',
            field=models.ManyToManyField(related_name='mod_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='owners',
            field=models.ManyToManyField(related_name='owned_orgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
