# Generated by Django 4.2.3 on 2023-07-03 20:18

from django.db import migrations
from django.contrib.postgres.operations import CITextExtension

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_delete_profile'),
    ]

    operations = [CITextExtension()]
