# Generated by Django 4.2.3 on 2023-07-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ktopic_created',
            field=models.BooleanField(default=False),
        ),
    ]
