# Generated by Django 4.2.3 on 2023-07-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_room_ktopic_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ktopic_created',
        ),
    ]
