# Generated by Django 4.2.4 on 2023-08-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_room_ktopic_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='morder',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
