# Generated by Django 4.2.4 on 2023-08-04 22:39

from django.db import migrations

def generate_morder(apps, schema_editor):
  Message = apps.get_model("chat", "Message")
  counter = 1
  for msg in Message.objects.all().order_by('time'):
    msg.morder = counter
    msg.save()
    counter += 1

class Migration(migrations.Migration):
  dependencies = [
    ('chat', '0012_message_morder'),
  ]

  operations = [
    migrations.RunPython(generate_morder)
  ]
