# Generated by Django 4.2.4 on 2023-08-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20230804_2239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('topic', 'morder')},
        ),
    ]
